Added side navbar
microembeddedtechnologies/rpi_ui pull request #5
Opened 2020-05-01 16:04 UTC by nsk515

## Due Date:

## Reviewers:
@roshnee7 

## Observers:

## Related Pull Requests:

## Description:

## Test Results:

2020-05-01 16:10 UTC, roshnee7 requested changes
minor changes.

2020-05-01 16:10 UTC, roshnee7 commented on src/Components/Charts.js
> +export default Charts;
fix end of file

2020-05-01 16:10 UTC, roshnee7 commented on src/Components/Configure.js
> +export default Configure;
fix end of file

2020-05-01 16:10 UTC, roshnee7 commented on src/Components/Home.js
> +export default Home;
fix end of file

2020-05-01 16:10 UTC, roshnee7 commented on src/Components/mainapp.js
> +export default MainApp
fix end of file

2020-05-02 06:13 UTC, nsk515 commented
@roshnee7 resolved. Please re-review.

2020-05-02 06:27 UTC, roshnee7 commented on src/Components/me_navbar.css
> +
add new line at end of line

2020-05-02 06:29 UTC, roshnee7 approved these changes

2020-05-02 06:29 UTC, merged